#!/bin/bash
set -e
export COLOUR_FAIL='\e[31m'
export COLOUR_SUCCESS='\e[32m'
export COLOUR_RESET='\e[0m'
printf 'Running: %b%s%b\n' "${COLOUR_SUCCESS}" "${0##*/}" "${COLOUR_RESET}"

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive
export APT_GET='apt-get install -yqq --no-install-recommends '
