#!/bin/bash
set -e
COLOUR_FAIL='\e[31m'
COLOUR_SUCCESS='\e[32m'
COLOUR_RESET='\e[0m'
printf 'Running: %b%s%b\n' $COLOUR_SUCCESS "${0##*/}" $COLOUR_RESET

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive
APT_GET='apt-get install -yqq --no-install-recommends '