FROM {{NODE_WITHOUT_BUILD_TOOLS}}

RUN apt-get -qq update && \
    apt-get -yq install --no-install-recommends \
        python \
        build-essential \
        && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/*

ONBUILD ADD ./ /app
